import '../../models/profile.dart';

const discoverProfiles = <DiscoverProfile>[
  DiscoverProfile(
    id: '1',
    name: 'Jelani',
    age: 27,
    location: 'Nairobi, Kenya',
    distance: '8 km away',
    imageUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=90',
    bio:
        'Creative soul, lover of travel, culture and meaningful conversations.',
    prompt: 'Jollof or waakye? Defend your choice.',
    interests: ['Amapiano', 'Highlife', 'Safari', 'Palm Wine', 'Pidgin'],
    verified: true,
    premium: true,
    smoking: 'Non-smoker',
    drinking: 'Social drinker',
    relationshipGoal: 'Long-term',
    educationLevel: 'Master\'s',
  ),
  DiscoverProfile(
    id: '2',
    name: 'Nadia',
    age: 25,
    location: 'Yaoundé',
    distance: '7 km away',
    imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=90',
    bio: 'Entrepreneur, foodie and always looking for the next adventure.',
    prompt: 'My ideal Sunday always includes good music.',
    interests: ['Foodie', 'Afrobeats', 'Travel'],
    verified: true,
    smoking: 'Social smoker',
    drinking: 'Social drinker',
    relationshipGoal: 'Dating',
    educationLevel: 'Bachelor\'s',
  ),
  DiscoverProfile(
    id: '3',
    name: 'Maya',
    age: 29,
    location: 'Buea',
    distance: '12 km away',
    imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=90',
    bio: 'Music, art, good energy and genuine connections.',
    prompt: 'The quickest way to my heart is laughter.',
    interests: ['Art', 'R&B', 'Coffee'],
    verified: true,
    smoking: 'Non-smoker',
    drinking: 'Non-drinker',
    relationshipGoal: 'Marriage',
    educationLevel: 'Doctorate',
  ),
  DiscoverProfile(
    id: '4',
    name: 'Arielle',
    age: 26,
    location: 'Limbe',
    distance: '18 km away',
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=90',
    bio: 'Beach lover with a soft spot for beautiful conversations.',
    prompt: 'Let’s trade hidden beach recommendations.',
    interests: ['Beach', 'Books', 'Sunsets'],
    smoking: 'Non-smoker',
    drinking: 'Social drinker',
    relationshipGoal: 'Long-term',
    educationLevel: 'Bachelor\'s',
  ),
];
